import { Injectable, inject } from '@angular/core';

import { Organization } from '../models/organization.model';

import { FirestoreOrganizationRepository } from '../repositories/firestore-organization.repository';

@Injectable({
  providedIn: 'root',
})
export class OrganizationService {

  private readonly repository =
    inject(
      FirestoreOrganizationRepository,
    );


  // =========================================================
  // GET ALL ORGANIZATIONS
  // =========================================================

  async getAllOrganizations(): Promise<Organization[]> {

    return this.repository.getOrganizations();

  }


  // =========================================================
  // GET ORGANIZATION BY ID
  // =========================================================

  async getOrganizationById(
    id: string,
  ): Promise<Organization | null> {

    return this.repository.getOrganization(
      id,
    );

  }


  // =========================================================
  // FIND ORGANIZATION BY NAME
  // =========================================================

  async findOrganizationByName(
    name: string,
  ): Promise<Organization | null> {

    const trimmedName =
      name.trim();

    if (!trimmedName) {
      return null;
    }

    const normalizedName =
      this.normalizeOrganizationName(
        trimmedName,
      );

    return this.repository.findByNormalizedName(
      normalizedName,
    );
  }


  // =========================================================
  // FIND ORGANIZATION BY COMPANY NUMBER
  // =========================================================

  async findOrganizationByCompanyNumber(
    companyNumber: string,
  ): Promise<Organization | null> {

    const normalizedNumber =
      companyNumber.trim();

    if (!normalizedNumber) {
      return null;
    }

    return this.repository.findByCompanyNumber(
      normalizedNumber,
    );
  }


  // =========================================================
  // FIND OR CREATE ORGANIZATION
  // =========================================================

  async findOrCreateOrganization(
    name: string,
    companyNumber?: string,
  ): Promise<Organization> {

    const trimmedName =
      name.trim();

    const trimmedCompanyNumber =
      companyNumber?.trim() || '';

    if (!trimmedName) {
      throw new Error(
        'Organization name is required.',
      );
    }


    // -------------------------------------------------------
    // First attempt: company / registration number
    // -------------------------------------------------------

    if (trimmedCompanyNumber) {

      const existingByNumber =
        await this.findOrganizationByCompanyNumber(
          trimmedCompanyNumber,
        );

      if (existingByNumber) {
        return existingByNumber;
      }
    }


    // -------------------------------------------------------
    // Second attempt: organization name
    // -------------------------------------------------------

    const existingByName =
      await this.findOrganizationByName(
        trimmedName,
      );

    if (existingByName) {

      /*
       * If the existing organization does not have
       * a company number, preserve the existing
       * organization and add the supplied number.
       */
      if (
        trimmedCompanyNumber &&
        !existingByName.companyNumber
      ) {

        await this.updateOrganization(
          existingByName.id,
          {
            companyNumber:
              trimmedCompanyNumber,
          },
        );

        existingByName.companyNumber =
          trimmedCompanyNumber;
      }

      return existingByName;
    }


    // -------------------------------------------------------
    // Create a new organization
    // -------------------------------------------------------

    const organizationData = {

      name:
        trimmedName,

      slug:
        this.createSlug(
          trimmedName,
        ),

      normalizedName:
        this.normalizeOrganizationName(
          trimmedName,
        ),

      ...(trimmedCompanyNumber
        ? {
            companyNumber:
              trimmedCompanyNumber,
          }
        : {}),

      verified:
        false,

      active:
        true,
    };


    const organizationId =
      await this.createOrganization(
        organizationData,
      );


    return {
      id:
        organizationId,

      ...organizationData,

      /*
       * The Firestore timestamps are generated by
       * serverTimestamp(). They are therefore not
       * available synchronously here.
       */
      createdAt:
        undefined as never,

      updatedAt:
        undefined as never,
    };
  }


  // =========================================================
  // CREATE
  // =========================================================

  async createOrganization(
    organization: Omit<
      Organization,
      'id' | 'createdAt' | 'updatedAt'
    >,
  ): Promise<string> {

    return this.repository.createOrganization(
      organization,
    );

  }


  // =========================================================
  // UPDATE
  // =========================================================

  async updateOrganization(
    organizationId: string,

    organization: Partial<
      Omit<
        Organization,
        'id' | 'createdAt' | 'updatedAt'
      >
    >,
  ): Promise<void> {

    return this.repository.updateOrganization(
      organizationId,
      organization,
    );

  }


  // =========================================================
  // DELETE
  // =========================================================

  async deleteOrganization(
    organizationId: string,
  ): Promise<void> {

    return this.repository.deleteOrganization(
      organizationId,
    );

  }


  // =========================================================
  // NORMALIZE ORGANIZATION NAME
  // =========================================================

  private normalizeOrganizationName(
    name: string,
  ): string {

    return name
      .trim()
      .toLowerCase()
      .replace(
        /\s+/g,
        ' ',
      );
  }


  // =========================================================
  // CREATE SLUG
  // =========================================================

  private createSlug(
    name: string,
  ): string {

    return this.normalizeOrganizationName(
      name,
    )
      .replace(
        /[^a-z0-9]+/g,
        '-',
      )
      .replace(
        /^-+|-+$/g,
        '',
      );
  }
}