/** * Classification of an operational event. * * Keep this provider-agnostic. These values represent * application/business concepts rather than Firebase concepts. */
export type OperationalEventType =

    | 'incident'
    | 'error'
    | 'failed-operation'
    | 'infrastructure'
    | 'background-job'
    | 'security'
    | 'system'
    | 'user-report';

/** * Operational severity. */
export type OperationalEventSeverity =
  | 'info'
  | 'warning'
  | 'error'
  | 'critical';

/** * Lifecycle state of an operational event. */
export type OperationalEventStatus =
  | 'open'
  | 'investigating'
  | 'acknowledged'
  | 'resolved'
  | 'closed';

/** * Where an operational event originated. */
export type OperationalEventSource =
  | 'application'
  | 'backend'
  | 'database'
  | 'authentication'
  | 'storage'
  | 'external-service'
  | 'scheduler'
  | 'user'
  | 'system';

/** * Provider-agnostic operational event. * * This is the domain representation used throughout Zebron. * It should NOT contain Firebase DocumentReference, Timestamp, * or other provider-specific types. */ export interface OperationalEvent {
  id: string;
  type: OperationalEventType;
  severity: OperationalEventSeverity;
  status: OperationalEventStatus;
  source: OperationalEventSource;
  /** * Short human-readable title. */ title: string;
  /** * Detailed description of the event. */ description?: string;
  /** * Feature/module associated with the event. * * Examples: * - community * - tax-pay-calculator * - authentication * - test-center */ feature?: string;
  /** * Application/service that generated the event. */ service?: string;
  /** * Optional operation name. * * Example: * createDonationCheckout */ operation?: string;
  /** * User associated with the event, when applicable. */ userId?: string;
  /** * Human-readable user information should not be * stored here unless explicitly required. */ correlationId?: string;
  /** * Optional technical error information. * * Do not place secrets, tokens, passwords, or * sensitive authentication information here. */ errorCode?: string;
  errorMessage?: string;
  /** * Structured diagnostic information. * * Keep this serializable and provider-agnostic. */ metadata?: Record<
    string,
    unknown
  >;
  /** * Number of times the same event has been observed, * when aggregation is being used. */ occurrenceCount?: number;
  /** * Event creation timestamp. * * Stored as an ISO string at the domain layer so the * domain model remains provider-independent. */ createdAt: string;
  /** * Last time the event was updated. */ updatedAt: string;
  /** * Time at which the event was acknowledged. */ acknowledgedAt?: string;
  /** * Time at which the event was resolved. */ resolvedAt?: string;
  /** * User/admin who acknowledged the event. */ acknowledgedBy?: string;
  /** * User/admin who resolved the event. */ resolvedBy?: string;
}
/** * Input used when creating a new operational event. * * id/timestamps/status are generated by the service/repository. */ export interface CreateOperationalEventInput {
  type: OperationalEventType;
  severity: OperationalEventSeverity;
  source: OperationalEventSource;
  title: string;
  description?: string;
  feature?: string;
  service?: string;
  operation?: string;
  userId?: string;
  correlationId?: string;
  errorCode?: string;
  errorMessage?: string;
  metadata?: Record<string, unknown>;
}

/** * Fields that administrators can update while * investigating an operational event. */ export interface UpdateOperationalEventInput {
  status?: OperationalEventStatus;
  severity?: OperationalEventSeverity;
  description?: string;
  metadata?: Record<string, unknown>;
  acknowledgedBy?: string;
  resolvedBy?: string;
}

/** * Filtering options for operational monitoring. */ export interface OperationalEventQuery {
  type?: OperationalEventType;
  severity?: OperationalEventSeverity;
  status?: OperationalEventStatus;
  source?: OperationalEventSource;
  feature?: string;
  service?: string;
  userId?: string;
  startDate?: string;
  endDate?: string;
  limit?: number;
}
