import {
  Permission,
  PERMISSIONS,
} from './permission.model';

export type PlatformRole =
  | 'platform-admin'
  | 'platform-operator'
  | 'platform-support'
  | 'platform-auditor';

export type OrganizationRole =
  | 'owner'
  | 'admin'
  | 'manager'
  | 'member';

export const PLATFORM_ROLE_PERMISSIONS:
  Record<PlatformRole, Permission[]> = {
  'platform-admin': [
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.APPLICATIONS_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.FEATURES_VIEW,
    PERMISSIONS.FEATURES_MANAGE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ORGANIZATIONS_VIEW,
    PERMISSIONS.ORGANIZATIONS_MANAGE,
    PERMISSIONS.TAX_RULES_VIEW,
    PERMISSIONS.TAX_RULES_MANAGE,
    PERMISSIONS.TAX_RULES_PUBLISH,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.OPERATIONS_EXECUTE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.SECURITY_MANAGE,
  ],

  'platform-operator': [
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.APPLICATIONS_MANAGE,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.FEATURES_VIEW,
    PERMISSIONS.FEATURES_MANAGE,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.OPERATIONS_EXECUTE,
    PERMISSIONS.AUDIT_VIEW,
  ],

  'platform-support': [
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.FEATURES_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.ORGANIZATIONS_VIEW,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],

  'platform-auditor': [
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.FEATURES_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.ORGANIZATIONS_VIEW,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SECURITY_VIEW,
  ],
};

export const ORGANIZATION_ROLE_PERMISSIONS:
  Record<OrganizationRole, Permission[]> = {
  owner: [
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.FEATURES_VIEW,
    PERMISSIONS.FEATURES_MANAGE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ORGANIZATIONS_VIEW,
    PERMISSIONS.ORGANIZATIONS_MANAGE,
  ],

  admin: [
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.FEATURES_VIEW,
    PERMISSIONS.FEATURES_MANAGE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ORGANIZATIONS_VIEW,
  ],

  manager: [
    PERMISSIONS.APPLICATIONS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.FEATURES_VIEW,
    PERMISSIONS.USERS_VIEW,
  ],

  member: [
    PERMISSIONS.APPLICATIONS_VIEW,
  ],
};