/**
 * GENERATED FILE
 *
 * DO NOT EDIT MANUALLY.
 *
 * Generated by:
 * scripts/generate-application-inventory.mjs
 *
 * Generated at:
 * 2026-09-20T17:48:34.668Z
 */

import type {
  ApplicationImplementationManifest,
} from '../models/application-implementation.model';

export const GENERATED_APPLICATION_IMPLEMENTATION_MANIFESTS:
  ApplicationImplementationManifest[] = [
  {
    "applicationKey": "community",
    "applicationName": "Community",
    "description": "Community application implementation inventory.",
    "dependencies": [
      {
        "id": "community.component.community.chat.components.chat_call_panel.chat_call_panel.component",
        "applicationKey": "community",
        "name": "Chat Call Panel",
        "path": "src/app/features/community/chat/components/chat-call-panel/chat-call-panel.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.chat.components.chat_list.chat_list.component",
        "applicationKey": "community",
        "name": "Chat List",
        "path": "src/app/features/community/chat/components/chat-list/chat-list.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.chat.components.chat_window.chat_window.component",
        "applicationKey": "community",
        "name": "Chat Window",
        "path": "src/app/features/community/chat/components/chat-window/chat-window.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.chat.components.new_conversation_dialog.new_conversation_dialog.component",
        "applicationKey": "community",
        "name": "New Conversation Dialog",
        "path": "src/app/features/community/chat/components/new-conversation-dialog/new-conversation-dialog.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.chat.models.chat_call.model",
        "applicationKey": "community",
        "name": "Chat Call",
        "path": "src/app/features/community/chat/models/chat-call.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.chat.models.chat_conversation.model",
        "applicationKey": "community",
        "name": "Chat Conversation",
        "path": "src/app/features/community/chat/models/chat-conversation.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.chat.models.chat_message.model",
        "applicationKey": "community",
        "name": "Chat Message",
        "path": "src/app/features/community/chat/models/chat-message.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.chat.models.chat_participant.model",
        "applicationKey": "community",
        "name": "Chat Participant",
        "path": "src/app/features/community/chat/models/chat-participant.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.chat.pages.community_chat.community_chat.component",
        "applicationKey": "community",
        "name": "Community Chat",
        "path": "src/app/features/community/chat/pages/community-chat/community-chat.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.chat.services.chat_call.service",
        "applicationKey": "community",
        "name": "Chat Call",
        "path": "src/app/features/community/chat/services/chat-call.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.chat.services.chat.service",
        "applicationKey": "community",
        "name": "Chat",
        "path": "src/app/features/community/chat/services/chat.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.store.community.chat.store.chat.store",
        "applicationKey": "community",
        "name": "Chat",
        "path": "src/app/features/community/chat/store/chat.store.ts",
        "type": "store",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.components.community_comment.community_comment.component",
        "applicationKey": "community",
        "name": "Community Comment",
        "path": "src/app/features/community/components/community-comment/community-comment.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.components.community_feed.community_feed.component",
        "applicationKey": "community",
        "name": "Community Feed",
        "path": "src/app/features/community/components/community-feed/community-feed.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.components.community_post_card.community_post_card.component",
        "applicationKey": "community",
        "name": "Community Post Card",
        "path": "src/app/features/community/components/community-post-card/community-post-card.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.components.community_post_composer.community_post_composer.component",
        "applicationKey": "community",
        "name": "Community Post Composer",
        "path": "src/app/features/community/components/community-post-composer/community-post-composer.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.components.community_sidebar.community_sidebar.component",
        "applicationKey": "community",
        "name": "Community Sidebar",
        "path": "src/app/features/community/components/community-sidebar/community-sidebar.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.components.community_trending.community_trending.component",
        "applicationKey": "community",
        "name": "Community Trending",
        "path": "src/app/features/community/components/community-trending/community-trending.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_bookmark.model",
        "applicationKey": "community",
        "name": "Community Bookmark",
        "path": "src/app/features/community/models/community-bookmark.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_comment.model",
        "applicationKey": "community",
        "name": "Community Comment",
        "path": "src/app/features/community/models/community-comment.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_conversation.model",
        "applicationKey": "community",
        "name": "Community Conversation",
        "path": "src/app/features/community/models/community-conversation.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_feed.model",
        "applicationKey": "community",
        "name": "Community Feed",
        "path": "src/app/features/community/models/community-feed.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_follow.model",
        "applicationKey": "community",
        "name": "Community Follow",
        "path": "src/app/features/community/models/community-follow.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_message.model",
        "applicationKey": "community",
        "name": "Community Message",
        "path": "src/app/features/community/models/community-message.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_notification.model",
        "applicationKey": "community",
        "name": "Community Notification",
        "path": "src/app/features/community/models/community-notification.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_post.model",
        "applicationKey": "community",
        "name": "Community Post",
        "path": "src/app/features/community/models/community-post.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_reaction.model",
        "applicationKey": "community",
        "name": "Community Reaction",
        "path": "src/app/features/community/models/community-reaction.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_topic.model",
        "applicationKey": "community",
        "name": "Community Topic",
        "path": "src/app/features/community/models/community-topic.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.model.community.models.community_user.model",
        "applicationKey": "community",
        "name": "Community User",
        "path": "src/app/features/community/models/community-user.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.pages.community_home.community_home.component",
        "applicationKey": "community",
        "name": "Community Home",
        "path": "src/app/features/community/pages/community-home/community-home.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.pages.community_members.community_members.component",
        "applicationKey": "community",
        "name": "Community Members",
        "path": "src/app/features/community/pages/community-members/community-members.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.pages.community_notifications.community_notifications.component",
        "applicationKey": "community",
        "name": "Community Notifications",
        "path": "src/app/features/community/pages/community-notifications/community-notifications.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.pages.community_post_detail.community_post_detail.component",
        "applicationKey": "community",
        "name": "Community Post Detail",
        "path": "src/app/features/community/pages/community-post-detail/community-post-detail.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.component.community.pages.community_user_profile.community_user_profile.component",
        "applicationKey": "community",
        "name": "Community User Profile",
        "path": "src/app/features/community/pages/community-user-profile/community-user-profile.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_bookmark.service",
        "applicationKey": "community",
        "name": "Community Bookmark",
        "path": "src/app/features/community/services/community-bookmark.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_comment.service",
        "applicationKey": "community",
        "name": "Community Comment",
        "path": "src/app/features/community/services/community-comment.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_follow.service",
        "applicationKey": "community",
        "name": "Community Follow",
        "path": "src/app/features/community/services/community-follow.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_message.service",
        "applicationKey": "community",
        "name": "Community Message",
        "path": "src/app/features/community/services/community-message.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_notification.service",
        "applicationKey": "community",
        "name": "Community Notification",
        "path": "src/app/features/community/services/community-notification.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_post_view.service",
        "applicationKey": "community",
        "name": "Community Post View",
        "path": "src/app/features/community/services/community-post-view.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_post.service",
        "applicationKey": "community",
        "name": "Community Post",
        "path": "src/app/features/community/services/community-post.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_ranking.service",
        "applicationKey": "community",
        "name": "Community Ranking",
        "path": "src/app/features/community/services/community-ranking.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_reaction.service",
        "applicationKey": "community",
        "name": "Community Reaction",
        "path": "src/app/features/community/services/community-reaction.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_topic.service",
        "applicationKey": "community",
        "name": "Community Topic",
        "path": "src/app/features/community/services/community-topic.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.service.community.services.community_user.service",
        "applicationKey": "community",
        "name": "Community User",
        "path": "src/app/features/community/services/community-user.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.store.community.store.community_comment.store",
        "applicationKey": "community",
        "name": "Community Comment",
        "path": "src/app/features/community/store/community-comment.store.ts",
        "type": "store",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.store.community.store.community_follow.store",
        "applicationKey": "community",
        "name": "Community Follow",
        "path": "src/app/features/community/store/community-follow.store.ts",
        "type": "store",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.store.community.store.community_notification.store",
        "applicationKey": "community",
        "name": "Community Notification",
        "path": "src/app/features/community/store/community-notification.store.ts",
        "type": "store",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.store.community.store.community_post.store",
        "applicationKey": "community",
        "name": "Community Post",
        "path": "src/app/features/community/store/community-post.store.ts",
        "type": "store",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.store.community.store.community_reaction.store",
        "applicationKey": "community",
        "name": "Community Reaction",
        "path": "src/app/features/community/store/community-reaction.store.ts",
        "type": "store",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "community.store.community.store.community.store",
        "applicationKey": "community",
        "name": "Community",
        "path": "src/app/features/community/store/community.store.ts",
        "type": "store",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      }
    ]
  },
  {
    "applicationKey": "resources",
    "applicationName": "Resources",
    "description": "Resources application implementation inventory.",
    "dependencies": [
      {
        "id": "resources.component.resources.components.resource_card.resource_card.component",
        "applicationKey": "resources",
        "name": "Resource Card",
        "path": "src/app/features/resources/components/resource-card/resource-card.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "resources.component.resources.components.useful_links.useful_links.component",
        "applicationKey": "resources",
        "name": "Useful Links",
        "path": "src/app/features/resources/components/useful-links/useful-links.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "resources.component.resources.pages.resource_detail.resource_detail.component",
        "applicationKey": "resources",
        "name": "Resource Detail",
        "path": "src/app/features/resources/pages/resource-detail/resource-detail.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "resources.component.resources.pages.resource_list.resource_list.component",
        "applicationKey": "resources",
        "name": "Resource List",
        "path": "src/app/features/resources/pages/resource-list/resource-list.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "resources.store.resources.stores.resource.store",
        "applicationKey": "resources",
        "name": "Resource",
        "path": "src/app/features/resources/stores/resource.store.ts",
        "type": "store",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      }
    ]
  },
  {
    "applicationKey": "jobs",
    "applicationName": "Jobs",
    "description": "Jobs application implementation inventory.",
    "dependencies": [
      {
        "id": "jobs.component.jobs.pages.job_detail.job_detail.component",
        "applicationKey": "jobs",
        "name": "Job Detail",
        "path": "src/app/features/jobs/pages/job-detail/job-detail.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "jobs.store.jobs.stores.job.store",
        "applicationKey": "jobs",
        "name": "Job",
        "path": "src/app/features/jobs/stores/job.store.ts",
        "type": "store",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      }
    ]
  },
  {
    "applicationKey": "test-center",
    "applicationName": "Test Center",
    "description": "Test Center application implementation inventory.",
    "dependencies": [
      {
        "id": "test-center.model.test_center.models.test_attempt.model",
        "applicationKey": "test-center",
        "name": "Test Attempt",
        "path": "src/app/features/test-center/models/test-attempt.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.model.test_center.models.test_course.model",
        "applicationKey": "test-center",
        "name": "Test Course",
        "path": "src/app/features/test-center/models/test-course.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.service.test_center.models.test_question_bank_file.service",
        "applicationKey": "test-center",
        "name": "Test Question Bank File",
        "path": "src/app/features/test-center/models/test-question-bank-file.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.model.test_center.models.test_question_import.model",
        "applicationKey": "test-center",
        "name": "Test Question Import",
        "path": "src/app/features/test-center/models/test-question-import.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.model.test_center.models.test_question.model",
        "applicationKey": "test-center",
        "name": "Test Question",
        "path": "src/app/features/test-center/models/test-question.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.model.test_center.models.test_result.model",
        "applicationKey": "test-center",
        "name": "Test Result",
        "path": "src/app/features/test-center/models/test-result.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.model.test_center.models.test_topic.model",
        "applicationKey": "test-center",
        "name": "Test Topic",
        "path": "src/app/features/test-center/models/test-topic.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.component.test_center.pages.course_detail.course_detail.component",
        "applicationKey": "test-center",
        "name": "Course Detail",
        "path": "src/app/features/test-center/pages/course-detail/course-detail.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.component.test_center.pages.course_list.course_list.component",
        "applicationKey": "test-center",
        "name": "Course List",
        "path": "src/app/features/test-center/pages/course-list/course-list.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.component.test_center.pages.test_center_home.test_center_home.component",
        "applicationKey": "test-center",
        "name": "Test Center Home",
        "path": "src/app/features/test-center/pages/test-center-home/test-center-home.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.component.test_center.pages.test_practice.test_practice.component",
        "applicationKey": "test-center",
        "name": "Test Practice",
        "path": "src/app/features/test-center/pages/test-practice/test-practice.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.component.test_center.pages.test_results.test_results.component",
        "applicationKey": "test-center",
        "name": "Test Results",
        "path": "src/app/features/test-center/pages/test-results/test-results.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.component.test_center.pages.test_setup.test_setup.component",
        "applicationKey": "test-center",
        "name": "Test Setup",
        "path": "src/app/features/test-center/pages/test-setup/test-setup.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.service.test_center.services.test_course.service",
        "applicationKey": "test-center",
        "name": "Test Course",
        "path": "src/app/features/test-center/services/test-course.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.service.test_center.services.test_question_import.service",
        "applicationKey": "test-center",
        "name": "Test Question Import",
        "path": "src/app/features/test-center/services/test-question-import.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.service.test_center.services.test_question.service",
        "applicationKey": "test-center",
        "name": "Test Question",
        "path": "src/app/features/test-center/services/test-question.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.service.test_center.services.test_topic.service",
        "applicationKey": "test-center",
        "name": "Test Topic",
        "path": "src/app/features/test-center/services/test-topic.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "test-center.store.test_center.store.test.store",
        "applicationKey": "test-center",
        "name": "Test",
        "path": "src/app/features/test-center/store/test.store.ts",
        "type": "store",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      }
    ]
  },
  {
    "applicationKey": "tax-pay",
    "applicationName": "Tax & Pay",
    "description": "Tax & Pay application implementation inventory.",
    "dependencies": [
      {
        "id": "tax-pay.data.tax_pay_calculator.data.maryland_local_tax_rates.data",
        "applicationKey": "tax-pay",
        "name": "Maryland Local Tax Rates",
        "path": "src/app/features/tax-pay-calculator/data/maryland-local-tax-rates.data.ts",
        "type": "data",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "tax-pay.data.tax_pay_calculator.data.us_counties.data",
        "applicationKey": "tax-pay",
        "name": "Us Counties",
        "path": "src/app/features/tax-pay-calculator/data/us-counties.data.ts",
        "type": "data",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "tax-pay.model.tax_pay_calculator.models.tax_calculator_input.model",
        "applicationKey": "tax-pay",
        "name": "Tax Calculator Input",
        "path": "src/app/features/tax-pay-calculator/models/tax-calculator-input.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "tax-pay.model.tax_pay_calculator.models.tax_calculator_result.model",
        "applicationKey": "tax-pay",
        "name": "Tax Calculator Result",
        "path": "src/app/features/tax-pay-calculator/models/tax-calculator-result.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "tax-pay.model.tax_pay_calculator.models.tax_calculator_types.model",
        "applicationKey": "tax-pay",
        "name": "Tax Calculator Types",
        "path": "src/app/features/tax-pay-calculator/models/tax-calculator-types.model.ts",
        "type": "model",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "tax-pay.component.tax_pay_calculator.pages.tax_pay_calculator.tax_pay_calculator.component",
        "applicationKey": "tax-pay",
        "name": "Tax Pay Calculator",
        "path": "src/app/features/tax-pay-calculator/pages/tax-pay-calculator/tax-pay-calculator.component.ts",
        "type": "component",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "tax-pay.service.tax_pay_calculator.services.tax_calculator_configuration.service",
        "applicationKey": "tax-pay",
        "name": "Tax Calculator Configuration",
        "path": "src/app/features/tax-pay-calculator/services/tax-calculator-configuration.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "tax-pay.service.tax_pay_calculator.services.tax_calculator.service",
        "applicationKey": "tax-pay",
        "name": "Tax Calculator",
        "path": "src/app/features/tax-pay-calculator/services/tax-calculator.service.ts",
        "type": "service",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "source-tree"
        }
      },
      {
        "id": "tax-pay.data.src_app_features_tax-pay-calculator_data_tax-pay-configuration-2026_ts",
        "applicationKey": "tax-pay",
        "name": "tax-pay-configuration-2026.ts",
        "path": "src/app/features/tax-pay-calculator/data/tax-pay-configuration-2026.ts",
        "type": "data",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "filesystem"
        }
      },
      {
        "id": "tax-pay.data.src_app_features_tax-pay-calculator_data_maryland-local-tax-rates_data_ts",
        "applicationKey": "tax-pay",
        "name": "maryland-local-tax-rates.data.ts",
        "path": "src/app/features/tax-pay-calculator/data/maryland-local-tax-rates.data.ts",
        "type": "data",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "filesystem"
        }
      },
      {
        "id": "tax-pay.data.src_app_features_tax-pay-calculator_data_us-counties_data_ts",
        "applicationKey": "tax-pay",
        "name": "us-counties.data.ts",
        "path": "src/app/features/tax-pay-calculator/data/us-counties.data.ts",
        "type": "data",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "filesystem"
        }
      },
      {
        "id": "tax-pay.firestore-rule.firestore_rules",
        "applicationKey": "tax-pay",
        "name": "firestore.rules",
        "path": "firestore.rules",
        "type": "firestore-rule",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "filesystem"
        }
      },
      {
        "id": "tax-pay.firestore-index.firestore_indexes_json",
        "applicationKey": "tax-pay",
        "name": "firestore.indexes.json",
        "path": "firestore.indexes.json",
        "type": "firestore-index",
        "required": true,
        "status": "detected",
        "metadata": {
          "generated": true,
          "source": "filesystem"
        }
      }
    ]
  }
];
